import React from 'react';
import { ShieldCheck, Lock, HeartHandshake, FileCheck } from 'lucide-react';

const Privacy = () => {
  return (
    <div className="space-y-6 max-w-4xl mx-auto py-2">
      <div className="bg-white rounded-2xl border border-slate-200/80 p-8 shadow-sm warm-card-hover space-y-6">
        <div>
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-amber-50 text-amber-700 rounded-xl">
              <Lock className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-800">Privacy & Data Ethics Standards</h1>
              <p className="text-slate-500 text-xs mt-0.5 font-medium">
                National Helpline Against Atrocities (NHAA 14566) — AI-Assisted Vulnerability & Support System
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-6 text-slate-700 text-sm">
          <section className="bg-amber-50/80 border-l-4 border-amber-500 p-5 rounded-r-2xl shadow-sm">
            <h2 className="font-bold text-amber-900 text-base mb-1.5 flex items-center gap-2">
              <HeartHandshake className="w-5 h-5 text-amber-700" />
              Human-in-the-Loop Safeguard
            </h2>
            <p className="text-amber-800 text-xs leading-relaxed font-medium">
              All AI outputs generated by this system (including SVI vulnerability scores, emotion analysis, risk classifications, and support recommendations) serve exclusively as decision-support tools for trained human operators and case managers. Final decisions regarding intervention, escalation, legal aid, or resource allocation are made solely by authorized personnel.
            </p>
          </section>

          <section className="space-y-2.5 bg-stone-50/70 p-5 rounded-xl border border-stone-200/70">
            <h2 className="font-bold text-slate-800 text-base border-b border-slate-200/70 pb-2">1. Data Minimization & Storage</h2>
            <p className="leading-relaxed text-xs text-slate-600 font-medium">
              The system processes call transcripts, voice audio, and survivor intake reports solely for the purpose of computing stress vulnerability index scores and formulating tailored relief actions. All sensitive identifying information (PII) is encrypted at rest using AES-256 standards.
            </p>
          </section>

          <section className="space-y-2.5 bg-stone-50/70 p-5 rounded-xl border border-stone-200/70">
            <h2 className="font-bold text-slate-800 text-base border-b border-slate-200/70 pb-2">2. Explainable SVI Scoring</h2>
            <p className="leading-relaxed text-xs text-slate-600 font-medium">
              Every score produced by the Stress Vulnerability Index (SVI) module is completely deterministic, auditable, and transparent. The system maintains a detailed breakdown of factor weights, risk multipliers, and safety overrides to eliminate black-box decision bias.
            </p>
          </section>

          <section className="space-y-2.5 bg-stone-50/70 p-5 rounded-xl border border-stone-200/70">
            <h2 className="font-bold text-slate-800 text-base border-b border-slate-200/70 pb-2">3. Role-Based Access Control (RBAC)</h2>
            <p className="leading-relaxed text-xs text-slate-600 font-medium">
              Access to case records and operational dashboards is strictly regulated according to user roles (e.g., Intake Operator, Senior Evaluator, Admin). Audit logs automatically record every read, update, override, and referral action taken within the platform.
            </p>
          </section>

          <section className="space-y-2.5 bg-stone-50/70 p-5 rounded-xl border border-stone-200/70">
            <h2 className="font-bold text-slate-800 text-base border-b border-slate-200/70 pb-2">4. Multi-lingual Fairness</h2>
            <p className="leading-relaxed text-xs text-slate-600 font-medium">
              NLP emotion detection and keyword extraction algorithms support 11 regional Indian languages with localized dialect sentiment normalizers to ensure equitable support allocation across diverse communities.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
